# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\liberal\Desktop\mooetest\pyqt\dirview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot


class Ui_Dir_view_window(object):
    def setupUi(self, Dir_view_window):
        Dir_view_window.setObjectName("Dir_view_window")
        Dir_view_window.resize(920, 673)
        Dir_view_window.setStyleSheet("")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dir_view_window)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.win_widget = QtWidgets.QWidget(Dir_view_window)
        self.win_widget.setObjectName("win_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.win_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.head_widget = QtWidgets.QWidget(self.win_widget)
        self.head_widget.setObjectName("head_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.head_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.window_icon = QtWidgets.QLabel(self.head_widget)
        self.window_icon.setMinimumSize(QtCore.QSize(40, 40))
        self.window_icon.setMaximumSize(QtCore.QSize(40, 40))
        self.window_icon.setObjectName("window_icon")
        self.horizontalLayout.addWidget(self.window_icon)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.window_title = QtWidgets.QLabel(self.head_widget)
        self.window_title.setMinimumSize(QtCore.QSize(20, 20))
        self.window_title.setMaximumSize(QtCore.QSize(500, 30))
        self.window_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.window_title.setAlignment(QtCore.Qt.AlignCenter)
        self.window_title.setObjectName("window_title")
        self.horizontalLayout.addWidget(self.window_title)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.min_window = QtWidgets.QPushButton(self.head_widget)
        self.min_window.setMinimumSize(QtCore.QSize(20, 20))
        self.min_window.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.min_window.setFont(font)
        self.min_window.setStyleSheet("")
        self.min_window.setObjectName("min_window")
        self.horizontalLayout.addWidget(self.min_window)
        self.max_window = QtWidgets.QPushButton(self.head_widget)
        self.max_window.setMinimumSize(QtCore.QSize(20, 20))
        self.max_window.setMaximumSize(QtCore.QSize(20, 20))
        self.max_window.setObjectName("max_window")
        self.horizontalLayout.addWidget(self.max_window)
        self.close_window = QtWidgets.QPushButton(self.head_widget)
        self.close_window.setMinimumSize(QtCore.QSize(20, 20))
        self.close_window.setMaximumSize(QtCore.QSize(20, 20))
        self.close_window.setObjectName("close_window")
        self.horizontalLayout.addWidget(self.close_window)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 15)
        self.horizontalLayout.setStretch(3, 30)
        self.horizontalLayout.setStretch(4, 15)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(6, 1)
        self.horizontalLayout.setStretch(7, 1)
        self.horizontalLayout.setStretch(8, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.head_widget)
        self.centralWidget = QtWidgets.QWidget(self.win_widget)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 0, 11, 11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_ip = QtWidgets.QLabel(self.centralWidget)
        self.label_ip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ip.setObjectName("label_ip")
        self.gridLayout.addWidget(self.label_ip, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 5, 1, 1)
        self.label_progess = QtWidgets.QLabel(self.centralWidget)
        self.label_progess.setObjectName("label_progess")
        self.gridLayout.addWidget(self.label_progess, 0, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(140, 16777215))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setMinimumSize(QtCore.QSize(0, 10))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setStyleSheet("QListWidget\n"
                                      "{\n"
                                      "    border:1px solid gray;   /*边界线:宽度、颜色*/\n"
                                      "    background:gray;    /*表格背景色*/\n"
                                      "    color:black;        /*前景色：文字颜色*/\n"
                                      "    /*margin:5px,5px,0px,50px;*/   /*上、下、左、右，间距*/\n"
                                      "}\n"
                                      "\n"
                                      "/*\n"
                                      "QListWidget::item\n"
                                      "{\n"
                                      "    padding-top:24px;\n"
                                      "    padding-bottom:4px;\n"
                                      "}\n"
                                      "*/\n"
                                      "\n"
                                      "QListWidget::item:hover\n"
                                      "{\n"
                                      "    show-decoration-selected:5;\n"
                                      "    background:skyblue;\n"
                                      "}\n"
                                      "\n"
                                      "QListWidget::item:selected\n"
                                      "{\n"
                                      "    /*border:0px;*/\n"
                                      "    background:lightgray;\n"
                                      "    padding:0px;\n"
                                      "    margin:0px;\n"
                                      "    color:red;\n"
                                      "}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_3.addWidget(self.centralWidget)
        self.verticalLayout_4.addWidget(self.win_widget)

        self.retranslateUi(Dir_view_window)
        QtCore.QMetaObject.connectSlotsByName(Dir_view_window)

    def retranslateUi(self, Dir_view_window):
        _translate = QtCore.QCoreApplication.translate
        Dir_view_window.setWindowTitle(_translate("Dir_view_window", "日志下载助手"))
        self.window_icon.setText(_translate("Dir_view_window", "图标"))
        self.window_title.setText(_translate("Dir_view_window", "标题"))
        self.min_window.setToolTip(_translate("Dir_view_window", "<html><head/><body><p>最小化</p></body></html>"))
        self.min_window.setText(_translate("Dir_view_window", "0"))
        self.max_window.setToolTip(_translate("Dir_view_window", "<html><head/><body><p>最大化</p></body></html>"))
        self.max_window.setText(_translate("Dir_view_window", "1"))
        self.close_window.setToolTip(_translate("Dir_view_window", "<html><head/><body><p>关闭</p></body></html>"))
        self.close_window.setText(_translate("Dir_view_window", "r"))
        self.label_ip.setText(_translate("Dir_view_window", "机器人ip:"))
        self.label_progess.setText(_translate("Dir_view_window", "下载进度:"))
        self.pushButton.setText(_translate("Dir_view_window", "解压日志"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dir_view_window = QtWidgets.QWidget()
    ui = Ui_Dir_view_window()
    ui.setupUi(Dir_view_window)
    Dir_view_window.show()
    sys.exit(app.exec_())
